name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  IMAGE_TAG: rodinandrei/bitforge-lending:${{ steps.commit.outputs.short }}
  SWARM_SERVICE: API_GATEWAY_nginx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: commit
      uses: prompt/actions-commit-hash@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{secrets.DOCKER_HUB_PASS}}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
       context: .
       push: true
       tags: ${{ env.IMAGE_TAG }}
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Update Swarm Service
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SWARM_MANAGER_HOST }}
        username: ${{ secrets.SWARM_MANAGER_LOGIN }}
        password: ${{ secrets.SWARM_MANAGER_PASS }}
        port: 22
        script: docker service update --image ${{ env.IMAGE_TAG }} ${{ env.SWARM_SERVICE }} 
