name: Docker Image CI
on:
  push:
    branches: [ "main" ]
env:
  SWARM_SERVICE: bf_landing
  DOCKER_HUB_REPO: rodinandrei
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{secrets.DOCKER_HUB_PASS}}
      - name: Create Tag
        id: create-tag
        run: echo tag=bf_landing:${{ steps.commit.outputs.short }} >> $GITHUB_OUTPUT
      - name: Build and push
        id: buildandpush
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}/${{ steps.create-tag.outputs.tag }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo ${{ needs.build.outputs.image_tag  }}
      - name: Update Swarm Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SWARM_MANAGER_HOST }}
          username: ${{ secrets.SWARM_MANAGER_LOGIN }}
          password: ${{ secrets.SWARM_MANAGER_PASS }}
          port: 22
          script: sudo docker service update --image ${{ env.DOCKER_HUB_REPO }}/${{ needs.build.outputs.image_tag}} ${{ env.SWARM_SERVICE }}
