name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t rodinandrei/bitforge-lending:latest
    - name: Login to the Docker Hub
      run: echo  ${{secrets.DOCKER_HUB_PASS}} | docker login --username ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin
    - name: Push the Docker image
      run: docker push rodinandrei/bitforge-lending:latest
